TravelMate/Controllers/CountryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TravelMate.Core.Contracts;
using TravelMate.Core.Models.CountryModels;

namespace TravelMate.Controllers
{
    [Authorize(Roles = "TravelGuru")]

    public class CountryController : Controller
    {
        private readonly ICountryService countryService;
        public CountryController(ICountryService _countryService)
        {
            this.countryService = _countryService;
        }

        public async Task<IActionResult> AllCountries()
        {
            var model = await countryService.GetAllCountries();

            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var model = new EditCountryViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(EditCountryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Add", model);
            }

            await countryService.Add(model);

            return RedirectToAction("AllCountries");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await countryService.GetCountryById(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditCountryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            await countryService.Edit(model);

            return RedirectToAction("AllCountries");
        }
    }
}

TravelMate/Controllers/FriendsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using TravelMate.Core.Constants;
using TravelMate.Core.Contracts;
using TravelMate.Extension;

namespace TravelMate.Controllers
{
    [Authorize]
    public class FriendsController : Controller
    {
        private readonly IFriendService friendService;

        public FriendsController(IFriendService _friendService)
        {
            this.friendService = _friendService;
        }

        public async Task<IActionResult> AddFriend(string id)
        {
            var userId = User.Id();

            if (await friendService.UsersAreFriends(userId, id))
            {
                TempData[MessageConstants.ErrorMessage] = "You are already friends";

                return RedirectToAction("ViewProfile", "Profile", new { @id = id });
            }

            if (userId == id)
            {
                TempData[MessageConstants.ErrorMessage] = "You cannot add yourseld as a friend";

                return RedirectToAction("ViewProfile", "Profile", new { @id = id });
            }

            await friendService.AddFriend(userId, id);

            TempData[MessageConstants.SuccessMessage] = "Successfully added to friends";

            return RedirectToAction("ViewProfile", "Profile", new { @id = id });
        }
                
        public async Task<IActionResult> ViewAllFriends(string id)
        {
            var model = await friendService.GetAllFriends(id);

            return View(model);
        }
    }
}

TravelMate/Controllers/LikeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TravelMate.Core.Constants;
using TravelMate.Core.Contracts;
using TravelMate.Extension;

namespace TravelMate.Controllers
{
    [Authorize]
    public class LikeController : Controller
    {
        private readonly ILikeService likeService;
        private readonly INotificationService notificationService;

        public LikeController(
            ILikeService _likeService,
            INotificationService _notificationService)
        {
            this.likeService = _likeService;
            this.notificationService = _notificationService;
        }
        public async Task<IActionResult> LikePost(int id)
        {
            var userId = User.Id();

            if (await likeService.UserLikedPost(id, userId))
            {
                TempData[MessageConstants.WarningMessage] = "Post is already liked!";

                return RedirectToAction("Index", "Home");
            }

            await likeService.AddLike(id, userId);

            TempData[MessageConstants.SuccessMessage] = "Post liked!";

            await notificationService.SendLikeNotification(id, userId);

            return RedirectToAction("Index", "Home");
        }
    }
}

TravelMate/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TravelMate.Core.Constants;
using TravelMate.Core.Contracts;
using TravelMate.Core.Models.Post;
using TravelMate.Extension;

namespace TravelMate.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly ICountryService countryService;
        private readonly ICategoryService categoryService;
        private readonly ILikeService likeService;
        private readonly INotificationService notificationService;
        private readonly IPhotoService photoService;

        public PostController(
            IPostService _postService,
            ICountryService _countryService,
            ICategoryService _categoryService,
            ILikeService _likeService,
            INotificationService _notificationService,
            IPhotoService _photoService)
        {
            this.postService = _postService;
            this.countryService = _countryService;
            this.categoryService = _categoryService;
            this.likeService = _likeService;
            this.notificationService = _notificationService;
            this.photoService = _photoService;
        }

        [HttpGet]
        public async Task<IActionResult> AddPost()
        {

            var categories = await categoryService.GetAllCategories();
            var countries = await countryService.GetAllCountries();

            var model = new CreatePostViewModel()
            {
                Categories = categories,
                Countries = countries
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddPost([FromForm] CreatePostViewModel post)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AddPost));
            }

            var userId = User.Id();
            var url = await photoService.UploadPhoto(post.File);

            try
            {
                await postService.CreatePost(post, userId, url);

                TempData[MessageConstants.SuccessMessage] = "Post successfully added!";

                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");

                return View(post);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await postService.GetPostById(id);

            if (model.AuthorId != User.Id())
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            var categories = await categoryService.GetAllCategories();
            var countries = await countryService.GetAllCountries();

            model.Categories = categories;
            model.Countries = countries;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditPostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            if (model.AuthorId != User.Id())
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            var url = await photoService.UploadPhoto(model.File);

            await postService.Edit(model, model.Id, url);

            TempData[MessageConstants.SuccessMessage] = "Post successfully edited!";

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await postService.GetPostInfoByPostId(id);

            if (User.Id() != model.AuthorId)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, PostViewModel model)
        {
            
            await postService.Delete(id);

            TempData[MessageConstants.SuccessMessage] = "Post successfully deleted!";

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> AllPosts([FromQuery] AllPostsQueryModel query)
        {
            var result = await postService.GetAllPostsQuery(query.Category, query.Country);

            query.Categories = await categoryService.GetAllCategoriesNames();
            query.Countries = await countryService.GetAllCountiresNames();
            query.Posts = result.Posts;

            return View(query);
        }

        public async Task<IActionResult> AllPostsOfUser(string id)
        {
            var model = await postService.GetAllPostsByUserId(id);

            return View(model);
        }
    }
}

TravelMate/Views/Shared/_CommentViewPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TravelMate.Infrastructure.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@model CommentViewModel

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="ViewProfile" asp-route-id="@Model.User.Id"><b>@Model.User.UserName</b></a>
        </div>
        <div class="col-md-2">
            <p>@Model.CreatedOn</p>
        </div>
        <div class="col-md-2">
            @if (UserManager.GetUserId(User) == Model.User.Id)
            {
                <p>Edit</p>
            }
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <p>@Model.Content</p>
        </div>
    </div>
</div>

TravelMate/Views/Shared/_FriendsListViewModel.cshtml
@model UserPostsViewModel

<div class="row">
    <div class="col-md-8">
        <h6>@Model.Username</h6>
    </div>
    <div class="col-md-2">
        <a asp-area="" asp-controller="Profile" asp-action="ViewProfile" asp-route-id="@Model.Id" class="btn btn-primary btn-sm">View profile</a>
    </div>
</div>

TravelMate/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using TravelMate.Infrastructure.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TravelMate</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TravelMate.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <partial name="_UserMessages">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TravelMate</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="AddPost">Share</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="AllPosts">Browse</a>
                        </li>
                            @if (this.User.IsInRole("TravelGuru") || this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Edit
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="AllCategories">Categories</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="AllCountries">Countries</a></li>
                                </ul>

                            </li>
                        }
                            @if (this.User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Area</a>
                                </li>
                            }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TravelMate
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TravelMate/Views/Shared/_NotificationPartial.cshtml
@model NotificationViewModel


<div class="row">
    <div class="col-md-8">
        <h6>@Model.Description</h6>
    </div>
    <div class="col-md-2">
        <a class="btn btn-primary btn-sm" asp-area="" asp-controller="Profile" asp-action="ViewProfile" asp-route-id="@Model.SenderId">View Profile</a>
    </div>
    <div class="col-md-2">
        @if (Model.NotificationType == 0)
        {
            <form asp-area="" asp-controller="Friends" asp-action="AddFriend" asp-route-id="@Model.SenderId" method="post">
                <input class="btn btn-success btn-sm" id="disable-button" type="submit" value="Add friend" />
            </form>
        }
    </div>
</div>

TravelMate/Views/Shared/_PostViewPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TravelMate.Infrastructure.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@model PostViewModel

<div class="card mb-3">
    <div class="row g-0">
        @if (!string.IsNullOrEmpty(Model.PhotoUrl))
        {
            <div class="col-md-4">
                <img class="card-img-top" src="@Model.PhotoUrl" alt="Post Image">
            </div>
        }
        else
        {
            <div class="col-md-4">
                <div class="card-img-top" style="background-color: white; height: 250px;"></div>
            </div>
        }
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">
                    <a href="@Url.Action("ViewProfile", "Profile", new { id = Model.AuthorId })">@Model.AuthorName</a>
                </h5>
                <p class="card-text">@Model.Content</p>
                <p class="card-text"><small class="text-muted">@Model.PostTime</small></p>
                <p class="card-text"><b>Location:</b> @Model.Country</p>
                <h6 class="card-subtitle mb-2 text-muted"><b>Category:</b> @Model.Category</h6>
                <p class="card-text"><b>Likes:</b> @Model.Likes</p>
                <br />
                @if (UserManager.GetUserId(User) != Model.AuthorId)
                {
                    <div class="btn-group btn-group-no-outline">
                        <a class="btn  btn-sm" asp-area="" asp-controller="Like" asp-action="LikePost" asp-route-id="@Model.Id">
                            <i class="fa-regular fa-thumbs-up"></i> <!-- Font Awesome icon for a thumb up -->
                        </a>
                        <a class="btn  btn-sm" asp-area="" asp-controller="Comments" asp-action="ViewPostComments" asp-route-id="@Model.Id">Comments (@Model.Comments)</a>
                    </div>
                }
                else
                {
                    <div class="btn-group btn-group-no-outline">
                        <a asp-area="" asp-controller="Post" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning btn-sm">Edit</a>
                        <a asp-area="" asp-controller="Post" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger btn-sm">Delete</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

TravelMate/Views/Shared/_UserMessages.cshtml
@using TravelMate.Core.Constants

@if (TempData[MessageConstants.ErrorMessage] != null)
{
    <script>
        $(function () {toastr.error('@TempData[MessageConstants.ErrorMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstants.WarningMessage] != null)
{
        <script>
            $(function () {toastr.warning('@TempData[MessageConstants.WarningMessage].ToString()'); });
        </script>
}

@if (TempData[MessageConstants.SuccessMessage] != null)
{
        <script>
            $(function () {toastr.success('@TempData[MessageConstants.SuccessMessage].ToString()'); });
        </script>
}